version: "2"
services:

  elasticsearch:
    image: elasticsearch:5.5.1
    expose:
      - 9200
      - 9300
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xms1g -Xmx1g"
      discovery.type: single-node
      cluster.name: elasticsearch
    #      ES_HEAP_SIZE: "2048m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    #    mem_limit: 2048m
    #    mem_reservation: 1600m
#    volumes:
#      - "/ext/elasticsearch:/usr/share/elasticsearch/data"
#      - "/opt/mcx/config/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml"
    networks:
      - backend
  # user: elastic, pass:changeme
  # before running ,run: sudo sysctl -w vm.max_map_count=262144
  kibana:
    image: kibana:5.5.1
    ports:
      - "5601:5601"
    links:
      - "elasticsearch"
    environment:
      ES_HEAP_SIZE: "2048m"
#    volumes:
#      - "/ext/elasticsearch:/var/lib/elasticsearch"
    networks:
      - backend
  fluentd:
    build: ./fluentd
    volumes:
      - ./fluentd/conf:/fluentd/etc
    links:
      - "elasticsearch"
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    networks:
      - backend

  pulsar-fluentd-consumer:
    build: .
    volumes:
      - ./fluentd/conf/fluentd-consumer.properties:/home/fluentd/fluentd-consumer.properties
    extra_hosts:
      - "pulsar:192.168.1.65"
    networks:
      - backend

  #  fluentd-es:
  #    image: openfirmware/fluentd-elasticsearch
  #    ports:
  #      - "24224:24224"
  #      - "8888:8888"
  #    links:
  #      - elk:elasticsearch
  #    networks:
  #      - backend
networks:
  backend:
    driver: bridge
